<html>
<head>
<title>JavaScript Clean Code: Error Handling</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">JavaScript干净代码:错误处理</h1>
<blockquote>原文：<a href="https://betterprogramming.pub/javascript-clean-code-error-handling-9cd7e87fdbe3?source=collection_archive---------5-----------------------#2020-03-11">https://betterprogramming.pub/javascript-clean-code-error-handling-9cd7e87fdbe3?source=collection_archive---------5-----------------------#2020-03-11</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><div class=""><h2 id="c9be" class="pw-subtitle-paragraph jq is it bd b jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh dk translated">我们着眼于处理错误的最佳方式</h2></div><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi ki"><img src="../Images/ddd9c48d7bff428aa3774a6fcf0adaa2.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*DVtAea-c73Lgu03qxovfUQ.jpeg"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">Max van den Oetelaar 在<a class="ae ky" href="https://unsplash.com/s/photos/patterns?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄的照片</p></figure><p id="cdb3" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">错误处理是程序的重要组成部分。在很多情况下，我们的程序会遇到意想不到的值，我们必须正确地处理它们。</p><p id="e0a6" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">在本文中，我们将研究如何处理它们，以便容易地发现错误并优雅地处理它们。</p></div><div class="ab cl lv lw hx lx" role="separator"><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma"/></div><div class="im in io ip iq"><h1 id="3ff5" class="mc md it bd me mf mg mh mi mj mk ml mm jz mn ka mo kc mp kd mq kf mr kg ms mt bi translated">异常比返回代码更好</h1><p id="00e4" class="pw-post-body-paragraph kz la it lb b lc mu ju le lf mv jx lh li mw lk ll lm mx lo lp lq my ls lt lu im bi translated">抛出异常更好，因为它们让我们知道存在错误，我们必须处理它。</p><p id="c925" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">大多数现代编程语言都有内置的异常，所以我们应该抛出它们，而不是返回一个错误代码。</p><p id="90c4" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">错误代码不明确，可能会被遗漏。异常也更加干净，因为我们不必检查所有可能返回的代码。</p><p id="0b6a" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">例如，如果我们在函数中返回错误代码，那么我们可能会得到如下代码:</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mz na l"/></div></figure><p id="baae" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们必须返回我们的<code class="fe nb nc nd ne b">setNumFruit</code>方法中的所有错误代码。同样，在我们做类定义之后的事情之前，我们必须检查所有的错误代码。</p><p id="d3d8" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们可以抛出异常来代替:</p><figure class="kj kk kl km gt kn"><div class="bz fp l di"><div class="mz na l"/></div></figure><p id="41c1" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们通过将想要运行的代码包装在一个<code class="fe nb nc nd ne b">try</code>块中，消除了检查所有错误代码的需要。现在我们可以捕捉错误，而不是检查所有可能返回的错误代码。</p><p id="0b04" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">这比在做某件事之前检查所有错误代码要好得多——当代码变得更加复杂时，这一点尤其重要。</p><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi nf"><img src="../Images/5b7f7fcea620d3dcbd62ed4526d126f8.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*_oeJImio2eNzM8fz"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated"><a class="ae ky" href="https://unsplash.com/@xoutcastx?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">泰勒</a>在<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄的照片</p></figure></div><div class="ab cl lv lw hx lx" role="separator"><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma"/></div><div class="im in io ip iq"><h1 id="1a06" class="mc md it bd me mf mg mh mi mj mk ml mm jz mn ka mo kc mp kd mq kf mr kg ms mt bi translated">编写Try-Catch-Finally</h1><p id="968d" class="pw-post-body-paragraph kz la it lb b lc mu ju le lf mv jx lh li mw lk ll lm mx lo lp lq my ls lt lu im bi translated">我们应该将我们的<code class="fe nb nc nd ne b">try</code>包装在抛出我们想要捕捉的异常的代码中。它为块范围的变量创建了自己的范围，所以用<code class="fe nb nc nd ne b">let</code>或<code class="fe nb nc nd ne b">const</code>声明的任何东西只能在<code class="fe nb nc nd ne b">try</code>块中引用。</p><p id="fa01" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">用<code class="fe nb nc nd ne b">var</code>声明的变量被提升，这样它们就可以在块外被引用。即使它们在块外被引用，我们也不会得到一个错误。这会让我们得到<code class="fe nb nc nd ne b">1</code>:</p><pre class="kj kk kl km gt ng ne nh ni aw nj bi"><span id="6fb6" class="nk md it ne b gy nl nm l nn no">try {<br/>  var x = 1;<br/>} catch (ex) {<br/>  console.error(ex);<br/>}<br/>console.log(x);</span></pre><p id="2dab" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">但这会让我们得到<code class="fe nb nc nd ne b">Uncaught ReferenceError: x is not defined</code>:</p><pre class="kj kk kl km gt ng ne nh ni aw nj bi"><span id="c398" class="nk md it ne b gy nl nm l nn no">try {<br/>  let x = 1;<br/>} catch (ex) {<br/>  console.error(ex);<br/>}<br/>console.log(x);</span></pre></div><div class="ab cl lv lw hx lx" role="separator"><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma"/></div><div class="im in io ip iq"><h1 id="830b" class="mc md it bd me mf mg mh mi mj mk ml mm jz mn ka mo kc mp kd mq kf mr kg ms mt bi translated">不要忽略捕获的错误</h1><p id="931b" class="pw-post-body-paragraph kz la it lb b lc mu ju le lf mv jx lh li mw lk ll lm mx lo lp lq my ls lt lu im bi translated">我们应该在发现错误时报告。他们不应该被抓住，然后被忽视。这是因为我们不想掩盖潜在的问题。</p><p id="39d2" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">报告异常让我们知道错误，然后相应地处理它。</p><p id="6458" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">上面的例子和<code class="fe nb nc nd ne b">console.error</code>一样，调用了以下内容:</p><pre class="kj kk kl km gt ng ne nh ni aw nj bi"><span id="8099" class="nk md it ne b gy nl nm l nn no">try {<br/>  const error = fruitStand.setNumFruit(1);<br/>  console.log(fruitStand.numFruits);<br/>} catch (ex) {<br/>  console.error(ex);<br/>}</span></pre><p id="58f1" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">这是报告错误的方法之一。我们也可以使用其他库在一个中心位置报告错误。</p></div><div class="ab cl lv lw hx lx" role="separator"><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma"/></div><div class="im in io ip iq"><h1 id="1b24" class="mc md it bd me mf mg mh mi mj mk ml mm jz mn ka mo kc mp kd mq kf mr kg ms mt bi translated">不要忽视被拒绝的承诺</h1><p id="949c" class="pw-post-body-paragraph kz la it lb b lc mu ju le lf mv jx lh li mw lk ll lm mx lo lp lq my ls lt lu im bi translated">像任何其他异常一样，被拒绝的承诺也需要处理。它们可以用我们传递给<code class="fe nb nc nd ne b">catch</code>方法的回调来处理，或者用<code class="fe nb nc nd ne b">try...catch</code>块来处理<code class="fe nb nc nd ne b">async</code>函数——它们是一样的。</p><p id="ae43" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">例如，我们可以通过编写以下内容来报告错误:</p><pre class="kj kk kl km gt ng ne nh ni aw nj bi"><span id="bd9a" class="nk md it ne b gy nl nm l nn no">Promise.reject('fail')<br/>  .catch(err =&gt; {<br/>    console.error(err);<br/>  })</span></pre><p id="4458" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">或者对于<code class="fe nb nc nd ne b">async</code>函数，我们可以这样写:</p><pre class="kj kk kl km gt ng ne nh ni aw nj bi"><span id="3b8c" class="nk md it ne b gy nl nm l nn no">(async () =&gt; {<br/>  try {<br/>    await Promise.reject('fail')<br/>  } catch (err) {<br/>    console.error(err);<br/>  }<br/>})()</span></pre></div><div class="ab cl lv lw hx lx" role="separator"><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma"/></div><div class="im in io ip iq"><h1 id="26fe" class="mc md it bd me mf mg mh mi mj mk ml mm jz mn ka mo kc mp kd mq kf mr kg ms mt bi translated">提供带有异常的上下文</h1><p id="aad8" class="pw-post-body-paragraph kz la it lb b lc mu ju le lf mv jx lh li mw lk ll lm mx lo lp lq my ls lt lu im bi translated">我们应该在异常中提供足够的上下文，以便其他开发人员可以在抛出异常时指出错误。</p><p id="8525" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们可以在JavaScript中获得异常的堆栈跟踪，但它可能不会提供我们需要的所有信息。</p></div><div class="ab cl lv lw hx lx" role="separator"><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma mb"/><span class="ly bw bk lz ma"/></div><div class="im in io ip iq"><h1 id="50b1" class="mc md it bd me mf mg mh mi mj mk ml mm jz mn ka mo kc mp kd mq kf mr kg ms mt bi translated">结论</h1><p id="bff1" class="pw-post-body-paragraph kz la it lb b lc mu ju le lf mv jx lh li mw lk ll lm mx lo lp lq my ls lt lu im bi translated">当我们处理错误时，抛出异常比返回错误代码要好，因为它们让我们使用<code class="fe nb nc nd ne b">try...catch</code>块来处理错误。这比检查多个错误代码要干净得多。</p><p id="4dd3" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">当我们抛出异常时，我们必须提供足够的细节来指出问题。</p><p id="c036" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">我们不应该在发现错误后就忽略它们。我们至少应该报告他们，这样他们才能被关注。</p><p id="7bf0" class="pw-post-body-paragraph kz la it lb b lc ld ju le lf lg jx lh li lj lk ll lm ln lo lp lq lr ls lt lu im bi translated">最后，被拒绝的承诺错误应该以与其他异常相同的方式处理。</p></div></div>    
</body>
</html>