# 如何在 Python 中处理和引发异常——需要知道的 12 件事

> 原文：<https://betterprogramming.pub/how-to-handle-and-raise-exceptions-in-python-12-things-to-know-4dfef7f02e4>

## 让您的 Python 代码更加健壮

![](img/4126c9543c37e3b733b58a659e64ab4c.png)

Photo by [傅甬 华](https://unsplash.com/@hhh13?utm_source=medium&utm_medium=referral) on [Unsplash](https://unsplash.com?utm_source=medium&utm_medium=referral)

当我们学习 Python 中的编码时，我们不可避免地会犯各种各样的错误，大多数时候是语法上的，有时是语义上的。例如，我不知道有多少次忘记了跟在`if`语句或函数声明后面的冒号，这导致了下面的`SyntaxError`:

句法误差

这些语法错误，也称为解析错误，在 Python 中通常由一个向上的小箭头表示，如上面的代码片段所示。除了配对错误之外，我们的代码可能包含更多逻辑问题的其他错误。例如，`TypeError`是我们经常遇到的另一个错误消息:

例外示例

在上面的代码片段中，我们试图连接字符串。然而，数字 2020 属于`int`类型，不能用于仅与`str`对象一起工作的字符串串联。在这种情况下，我们会遇到`TypeError`。用更精确的术语来说，`TypeError`异常是*引发的*或者 Python *引发*异常。

像`TypeError`一样，当 Python 试图执行这些代码行时，这些类型的错误(例如 `ValueError`和`ZeroDivisionError`)就会发生。在 Python 中，*我们通常将这些非语法错误称为异常，*使它们不同于语法错误。对于语法错误，我们必须使用可接受的语法来更新受影响的代码行。对于异常，我们可以通过适当实现相关技术来优雅地处理它们。

让我们先来看看如何处理异常。在后半部分，我们将学习 Python 中的异常引发。

# 异常处理

## 1.处理异常的基本形式

处理异常的标准方法是使用`try…except`块。如果你有这样的背景，它很像许多其他编程语言中的`try…catch`块。

`try`子句包含可能引发异常的代码。如果在`try`子句中一切正常，那么`except`子句中的任何代码都不会被执行。`try…except`程序块完成，程序将继续进行。

然而，如果在`try`子句中出现异常，Python 将停止执行该子句中的任何代码，并将异常传递给`except`子句，以查看该特定错误是否得到处理。

让我们来看一个最基本的异常处理形式的简单例子:

异常处理的基本形式

正如你所看到的，当除法按预期工作时，这个除法的结果(即 2.0)被打印出来。然而，当我们试图用零除这个数时，Python 抛出了`ZeroDivisionError`。幸运的是，我们的函数被编写来处理这个错误和消息“你不能用零除 12”打印出来通知用户这个错误。

## 2.为什么要处理异常？

我们现在了解了如何使用`try…except`块处理异常。但是我们为什么要费心处理异常呢？最重要的好处是通知用户错误，同时仍然允许程序继续运行。让我们看看一些类似的函数，有和没有处理异常:

异常已处理与未处理

如上所示，当我们调用处理异常的函数时，我们看到程序一直执行到函数结束(第 15–17 行)。相比之下，当我们调用不处理异常的函数时，我们看到程序不能完成到函数的结尾(第 18–22 行)。

## 3.变量赋值

我们可以将异常赋给一个变量，这样我们就可以检索关于异常的更多信息。在下面的代码中，我们可以将处理过的异常`TypeError`赋给变量`e`，这样我们就可以让 Python 为我们打印错误消息。如第 10 行所示，打印出错误消息，告诉我们不能将字符串与整数连接起来:

异常的变量赋值

## 4.多重例外

我们可以在`except`子句中处理多个异常。我们将简单地将可能的异常封装在一个元组中，如下面代码片段中的第 6 行所示。当我们调用该函数时，我们通过分别引发`ValueError`和`ZeroDivisionError`来故意制造两个不同的错误。这些消息清楚地告诉我们处理了什么异常。

多重例外

## 5.多重 except 子句

与上一节相关，当我们期望不同的异常时，我们实际上可以有多个`except`子句，每个子句处理一些特定的异常。让我们修改上面的函数(即`divide_six`)来创建除子句之外的多个*，如下所示。*

多重 Except 子句

修改之后，当我们两次调用该函数，并打算每次引发两个不同的异常时，将为每个`except`子句打印预期的消息。

## 6.else 子句

我们可以在`try…except`块中使用一个`else`子句。需要注意的是，`else`子句需要出现在`except`子句之后。当`try`子句完成且未引发任何异常时，`else`子句中的代码运行。让我们看看它的使用情况:

使用 Else 子句的异常处理

代码中有一个函数在`try…except`块中使用了一个`else`子句。如您所见，`else`子句中的代码仅在`try`子句完成且没有引发异常时运行。另一方面，当引发和处理异常时，代码不会运行。

## 7.finally 子句

除了使用`else`子句，我们还可以在`try…except`块中使用`finally`子句。请注意，`finally`子句需要放在块的末尾，在`except`子句或`else`子句(如果设置的话)的下面。`finally`子句中的代码将在整个`try…except`块完成之前运行(在执行`try`或`except`子句中的代码之后)。重要的是，`finally`子句中的代码将运行，而不管异常引发和处理状态如何。让我们看看它是如何工作的:

使用 Finally 子句处理异常

如上面的代码片段所示，我们有一个包含`finally`子句的函数。我们调用该函数两次，第二次调用引发异常。在这两种情况下，`finally`子句中的代码都能成功运行。

使用`finally`子句需要注意的另一件重要事情是，如果 try 子句包含一个`break`、`continue`和`return`语句，那么`finally`子句将在执行`break`、`continue`或`return`语句之前首先运行。这里很多人都会犯错。下面我们来看一个微不足道的例子:

执行顺序(最终)

# 引发异常

## 8.引发异常的基本形式

在上一节中，我们学习了在 Python 中使用`try…except`块处理异常的各种特性，这对于更健壮的代码来说肯定是必要的。但是，如果您知道如何正确地引发异常，您的代码还可以进一步增强。我们先来看一个基本形式:

引发异常:基本形式

如上图所示，我们使用了`raise`关键字(在其他编程语言中，它被称为`throw`)，后跟异常类(例如`Exception`、`NameError`)。我们也可以使用异常类构造函数来创建一个实例，就像`ValueError()`。这两种用法没有区别，前者只是后者使用构造函数的语法糖。

## 9.带有自定义消息的异常

我们还可以提供关于我们正在引发的异常的附加信息。最简单的方法就是使用异常类构造函数并包含适用的错误消息来创建实例。这非常简单:

自定义消息

## 10.再加注，然后冒泡

如图所示，所有的异常在被捕获时都会被处理。然而，我们可以重新引发异常，并将异常传递到外部范围，看看它是否可以被处理。这种将异常传递到外部的过程也称为冒泡或传播。

当我们编写包含嵌套结构的复杂代码时(例如，一个函数调用另一个函数，而另一个函数又可能调用另一个函数)，这个特性会更加有用。通过异常再引发，我们可以决定在哪里处理特定的异常。当然，处理特定异常的确切位置是根据具体情况决定的。在这里，我可以向您展示如何重新引发异常。我们先来看一些代码:

再次引发异常

在上面的代码中，我们有两个函数，`run_cast_number`调用另一个函数`cast_number`。我们用一个字符串调用这个函数两次，两次都导致了一个异常，因为这个异常是在`cast_number`函数中处理的，所以显示了消息“转换失败”。然而，第二次，我们调用函数，我们要求`cast_number`函数重新引发异常(第 8–9 行)，这样`except`子句在`run_cast_number`函数中运行(第 15&22–23 行)。

## 11.用户定义的异常

在许多情况下，我们可以使用[内置异常](https://docs.python.org/3/library/exceptions.html#bltin-exceptions)来帮助我们在项目中引发和处理异常。然而，Python 为我们提供了创建自定义异常类的灵活性。如果您不知道如何创建 Python 定制类，请参考我以前的相关文章:

[](https://medium.com/swlh/declare-your-first-python-class-understand-3-basic-components-15768c8d35b0) [## 声明您的第一个 Python 类——了解 3 个基本组件

### 使用自定义类更好地组织代码

medium.com](https://medium.com/swlh/declare-your-first-python-class-understand-3-basic-components-15768c8d35b0) 

具体来说，我们需要声明一个类作为内置`Exception`类的子类。按照惯例，您应该以 Error 结尾来命名您的类(例如，`MediumDataError`)。

自定义异常类

如上所示，我们创建了一个名为`FileExtensionError`的定制异常类。当我们抛出这样一个异常时，只使用类名是行不通的，如第 10–13 行所示。相反，我们应该通过为构造函数方法设置两个位置参数来实例化这个异常。如第 17 行所示，通过实现`__str__`方法，我们可以看到定制的异常消息。换句话说，异常消息是通过调用`str()`函数生成的。

## 12.何时加注

我们已经学习了如何引发内置和自定义异常。当我们学习 Python 的时候，很多时候，我们只需要知道如何处理异常。然而，随着您的 Python 技能的进步，您可能想知道何时应该引发异常。

经验法则是*当你的代码可能运行到某些无法继续执行的场景时，你应该抛出一个异常*。通过引发适当的异常，它将允许代码的其他部分正确处理异常，以便执行可以继续。

何时引发异常

在上面的代码中，我们首先定义了一个可以读取文件的函数`read_data`。假设另一个函数`process_data`是一个公共 API，我们不能很好地控制用户将要传递的文件类型。因此，当我们使用`read_data`函数读取数据时，我们想要引发一个异常，因为没有正确的数据，我们的程序无法继续运行。

我们调用公共 API `process_data`函数两次，一次使用错误的数据类型，另一次使用正确的数据类型。对于前一种情况，异常被正确地引发和处理，这样我们的程序就不会崩溃，并且用户也会被告知关于 API 使用的错误。

# 结论

在本文中，我们回顾了 Python 中处理和引发异常的各个方面。通过在项目中引入异常，您的代码将变得更加健壮，并且您不太可能遇到执行无法恢复的情况。

 [## 8.错误和异常- Python 3.8.3 文档

### 到目前为止，错误消息还没有被提及，但是如果你已经尝试过这些例子，你可能已经…

docs.python.org](https://docs.python.org/3/tutorial/errors.html)